import type { Metadata } from "next";
import { Geist, Geist_Mono, Changa } from "next/font/google";
import "./globals.css";
import { CountryContextProvider } from "@/context/CountryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const changa = Changa({
  subsets: ["latin"],
  variable: "--font-changa",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Vibra",
  description: "Generated by create next app",
    icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${changa.variable} antialiased`}
      >
        <CountryContextProvider>
        {children}
        </CountryContextProvider>
      </body>
    </html>
  );
}
